### ISSUE TITLE
Installation instructions link broken

### ISSUE THREAD

**Issue by sanyabt** [wdebeaum/drum#4]
Hi, the link for installation instructions in the README seems to be broken. Could you please share the instructions? Thanks!

**Comment by wdebeaum** [comment]
Sorry about that, the instructions moved to the trips-docs github wiki since our trac stopped working. I fixed the link in the README to reflect that.

**Comment by sanyabt** [comment]
Thank you! I actually started following the instructions on the trips-docs wiki and found some of the links to be broken (i.e. binary package of enju parser and the geonames file). Will the installation work without them or are they required? If so, do you have the updated links?

**Comment by sanyabt** [comment]
Thanks!
